spring.application.name=FairPartner-API
server.servlet.context-path=/api
server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/doc
springdoc.api-docs.path=/fairpartnerapi

app.security.jwt.secret=${KEY_SECRET}
app.security.jwt.expiration=86400

app.domain.group-max-participants=2