package com.ferrinsa.fairpartner.expense.service.domain.impl;

import com.ferrinsa.fairpartner.exception.expense.expensegroup.UserNotMemberOfGroupException;
import com.ferrinsa.fairpartner.exception.expense.settlement.*;
import com.ferrinsa.fairpartner.expense.dto.settlement.NewSettlementRequestDTO;
import com.ferrinsa.fairpartner.expense.dto.settlement.UpdateSettlementRequestDTO;
import com.ferrinsa.fairpartner.expense.model.Settlement;
import com.ferrinsa.fairpartner.expense.repository.ExpenseGroupRepository;
import com.ferrinsa.fairpartner.expense.repository.ParticipateRepository;
import com.ferrinsa.fairpartner.expense.repository.SettlementRepository;
import com.ferrinsa.fairpartner.expense.service.domain.SettlementService;
import com.ferrinsa.fairpartner.expense.service.domain.balance.BalanceService;
import com.ferrinsa.fairpartner.expense.service.domain.balance.model.UserBalanceResult;
import com.ferrinsa.fairpartner.user.repository.UserRepository;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.List;

@Service
public class SettlementServiceImpl implements SettlementService {
    // Used because createDate is generated by the DB; we refresh the entity to retrieve it before returning
    @PersistenceContext
    private EntityManager entityManager;

    // Use self injection to avoid "this" and ensure @Transactional is applied
    private final SettlementService self;
    private final SettlementRepository settlementRepository;
    private final ParticipateRepository participateRepository;
    private final ExpenseGroupRepository expenseGroupRepository;
    private final UserRepository userRepository;
    private final BalanceService balanceService;

    @Autowired
    public SettlementServiceImpl(@Lazy SettlementService self,
                                 SettlementRepository settlementRepository,
                                 ParticipateRepository participateRepository,
                                 ExpenseGroupRepository expenseGroupRepository,
                                 UserRepository userRepository,
                                 BalanceService balanceService) {
        this.self = self;
        this.settlementRepository = settlementRepository;
        this.participateRepository = participateRepository;
        this.expenseGroupRepository = expenseGroupRepository;
        this.userRepository = userRepository;
        this.balanceService = balanceService;
    }

    @Override
    @Transactional
    public Settlement createSettlement(Long userId, NewSettlementRequestDTO newSettlementRequestDTO) {
        this.validateParticipationUsers(userId,
                newSettlementRequestDTO.toUserId(),
                newSettlementRequestDTO.expenseGroupId());
        this.validateNewSettlementAgainstBalance(userId,
                newSettlementRequestDTO.expenseGroupId(),
                newSettlementRequestDTO.amount());

        Settlement settlement = new Settlement(
                expenseGroupRepository.getReferenceById(newSettlementRequestDTO.expenseGroupId()),
                userRepository.getReferenceById(userId),
                userRepository.getReferenceById(newSettlementRequestDTO.toUserId()),
                newSettlementRequestDTO.amount()
        );
        settlementRepository.save(settlement);
        entityManager.refresh(settlement);

        return settlement;
    }

    @Override
    public Settlement getSettlementById(Long userId, Long settlementId) {
        Settlement settlement = settlementRepository.findById(settlementId)
                .orElseThrow(() ->
                        new SettlementNotFoundException(String.valueOf(settlementId)));

        if (!participateRepository.existsByUserIdAndExpenseGroupId(userId, settlement.getExpenseGroup().getId())) {
            throw new UserNotMemberOfGroupException(
                    String.valueOf(userId),
                    String.valueOf(settlement.getExpenseGroup().getId()));
        }

        return settlement;
    }

    @Override
    public List<Settlement> findAllByGroupId(Long userId, Long expenseGroupId) {
        if (!participateRepository.existsByUserIdAndExpenseGroupId(userId, expenseGroupId)) {
            throw new UserNotMemberOfGroupException(
                    String.valueOf(userId),
                    String.valueOf(expenseGroupId));
        }

        return settlementRepository.findByExpenseGroupId(expenseGroupId);
    }

    @Override
    @Transactional
    public Settlement updateSettlement(Long userId,
                                       Long settlementId,
                                       UpdateSettlementRequestDTO updateSettlementRequestDTO) {
        Settlement settlementToUpdate = settlementRepository.findById(settlementId)
                .orElseThrow(() -> new SettlementNotFoundException(String.valueOf(settlementId)));

        if (!settlementToUpdate.getFromUser().getId().equals(userId)) {
            throw new SettlementOwnershipException();
        }

        self.deleteSettlement(userId, settlementId);
        NewSettlementRequestDTO dtoToCreateNewSettlement = new NewSettlementRequestDTO(
                settlementToUpdate.getExpenseGroup().getId(),
                settlementToUpdate.getToUser().getId(),
                updateSettlementRequestDTO.amount()
        );

        return self.createSettlement(userId, dtoToCreateNewSettlement);
    }

    @Override
    @Transactional
    public void deleteSettlement(Long userId, Long settlementId) {

        Settlement settlementToDelete = settlementRepository.findById(settlementId)
                .orElseThrow(() -> new SettlementNotFoundException(String.valueOf(settlementId)));

        if (!settlementToDelete.getFromUser().getId().equals(userId)) {
            throw new SettlementOwnershipException();
        }

        settlementRepository.delete(settlementToDelete);
    }

    private void validateParticipationUsers(Long fromUserId, Long toUserId, Long expenseGroupId) {
        if (!participateRepository.existsByUserIdAndExpenseGroupId(fromUserId, expenseGroupId)) {
            throw new UserNotMemberOfGroupException(
                    String.valueOf(fromUserId),
                    String.valueOf(expenseGroupId));
        }

        if (!participateRepository.existsByUserIdAndExpenseGroupId(toUserId, expenseGroupId)) {
            throw new UserNotMemberOfGroupException(
                    String.valueOf(toUserId),
                    String.valueOf(expenseGroupId));
        }

        if (participateRepository.countByExpenseGroup_Id(expenseGroupId) == 1) {
            throw new OnlyOneMemberException();
        }

        if (fromUserId.equals(toUserId)) {
            throw new SelfSettlementNotAllowedException();
        }

    }

    private void validateNewSettlementAgainstBalance(Long userId, Long expenseGroupId, BigDecimal settlementAmount) {
        List<UserBalanceResult> usersBalanceList = balanceService.obtainUsersBalance(expenseGroupId);
        for (UserBalanceResult userBalance : usersBalanceList) {
            if (userBalance.user().getId().equals(userId)) {
                this.validateUserIsDebtor(userBalance.balance());
                this.validateSettlementNotExceedingDebt(userBalance, settlementAmount);
                return;
            }
        }

        throw new UserNotMemberOfGroupException(String.valueOf(userId), String.valueOf(expenseGroupId));
    }

    private void validateSettlementNotExceedingDebt(UserBalanceResult userBalance, BigDecimal settlementAmount) {
        BigDecimal positiveDebt = userBalance.balance().abs();
        if (settlementAmount.compareTo(positiveDebt) > 0) {
            throw new DebtLimitExceededException();
        }
    }

    private void validateUserIsDebtor(BigDecimal balance) {
        if (balance.compareTo(BigDecimal.ZERO) > 0) {
            throw new NotUserDebtorException();
        } else if (balance.compareTo(BigDecimal.ZERO) == 0) {
            throw new NotDebtException();
        }
    }

}
