SET REFERENTIAL_INTEGRITY FALSE;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS participates;
DROP TABLE IF EXISTS payment;
DROP TABLE IF EXISTS expense;
DROP TABLE IF EXISTS expense_group;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS category;
SET REFERENTIAL_INTEGRITY TRUE;

CREATE TABLE users(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(20) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  registration_date DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE roles(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE user_roles (
  user_id INT,
  role_id INT,
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE expense_group(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description VARCHAR(200),
  icon VARCHAR(300) NOT NULL
);

CREATE TABLE participates (
  id_user INT,
  id_expense_group INT,
  PRIMARY KEY (id_user, id_expense_group),
  CONSTRAINT participates_user_fk FOREIGN KEY (id_user) REFERENCES users(id),
  CONSTRAINT participates_expense_group_fk FOREIGN KEY (id_expense_group) REFERENCES expense_group(id)
);

CREATE TABLE category(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(20) NOT NULL,
  icon VARCHAR(300) NOT NULL
);

CREATE TABLE expense (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_expense_group INT NOT NULL,
  id_category INT NOT NULL,
  id_user INT NOT NULL,
  name VARCHAR(20) NOT NULL,
  description VARCHAR(200),
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  icon VARCHAR(300) NOT NULL,
  cant DECIMAL(10,2) NOT NULL CHECK (cant > 0),
  CONSTRAINT expense_expense_group_fk FOREIGN KEY (id_expense_group) REFERENCES expense_group(id),
  CONSTRAINT expense_category_fk FOREIGN KEY (id_category) REFERENCES category(id),
  CONSTRAINT expense_user_fk FOREIGN KEY (id_user) REFERENCES users(id)
);

CREATE TABLE payment(
  id_user INT,
  id_expense INT,
  cant DECIMAL(10,2) NOT NULL CHECK (cant > 0),
  PRIMARY KEY (id_user, id_expense),
  CONSTRAINT payment_user_fk FOREIGN KEY (id_user) REFERENCES users(id),
  CONSTRAINT payment_expense_fk FOREIGN KEY (id_expense) REFERENCES expense(id)
);

